
@baseUrl = http://localhost:8080
@token = {{login.response.body.data.token}}

### Login
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "rakash2@example.com",
  "password": "password123"
}


### Register
# @name register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "name": "Rakashpal Singh",
  "email": "rakash2@example.com",
  "password": "password123"
}

### Account Creation
# @name Add  Account
POST {{baseUrl}}/api/accounts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "accountName": "Second Account",
  "accountType": "SAVINGS",
  "balance": 10000.00
}

### Account Get
# @name Get Added Account
GET  {{baseUrl}}/api/accounts
Content-Type: application/json
Authorization: Bearer {{token}}


